<a href="https://colab.research.google.com/github/Chizubaga/AutoCon/blob/main/Daksh_Sharma_DAY2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from tkinter import *
root=Tk()
root.title('Simple Calculator')
mainframe=Frame(root,width=45,bd=10, relief=RIDGE,bg='orange')
mainframe.pack()
inner=Frame(root,width=45,bd=10,relief=RIDGE,bg='cyan')
inner.pack()
e=Entry(inner,width=65,borderwidth=5)
e.grid(row=0,column=0,columnspan=4,padx=10,pady=1)
def onclick(num):
    x=e.get()
    e.delete(0,END)
    e.insert(0,str(x)+str(num))

def clear():
    e.delete(0,END)

def add():
    global first,op
    op='+'
    first=e.get()
    e.delete(0,END)

def sub():
    global first,op
    op='-'
    first=e.get()
    e.delete(0,END)

def mul():
    global first,op
    op='*'
    first=e.get()
    e.delete(0,END)

def div():
    global first,op
    op='/'
    first=e.get()
    e.delete(0,END)

def equal():
    second=e.get()
    if op=='+':
        result=float(first)+float(second)
    elif op=='-':
        result=float(first)-float(second)
    elif op=='*':
        result=float(first)*float(second)
    elif op=='/':
        result=float(first)/float(second)
    e.delete(0,END)
    e.insert(0,result)

button_1=Button(inner,text='1',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(1))

button_2=Button(inner,text='2',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(2))

button_3=Button(inner,text='3',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(3))

button_4=Button(inner,text='4',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(4))

button_5=Button(inner,text='5',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(5))

button_6=Button(inner,text='6',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(6))

button_7=Button(inner,text='7',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(7))

button_8=Button(inner,text='8',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(8))

button_9=Button(inner,text='9',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(9))

button_0=Button(inner,text='0',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=lambda:onclick(0))

button_add=Button(inner,text='+',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=add)
button_sub=Button(inner,text='-',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=sub)
button_mul=Button(inner,text='*',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=mul)
button_div=Button(inner,text='/',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=div)
button_equal=Button(inner,text='=',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=equal)
button_clear=Button(inner,text='C',padx=30,pady=10,relief=RIDGE,font=15,width=4,command=clear)

button_1.grid(row=3,column=0)
button_2.grid(row=3,column=1)
button_3.grid(row=3,column=2)
button_4.grid(row=2,column=0)
button_5.grid(row=2,column=1)
button_6.grid(row=2,column=2)
button_7.grid(row=1,column=0)
button_8.grid(row=1,column=1)
button_9.grid(row=1,column=2)
button_0.grid(row=4,column=0)
button_add.grid(row=1,column=3)
button_sub.grid(row=2,column=3)
button_mul.grid(row=3,column=3)
button_div.grid(row=4,column=3)
button_equal.grid(row=4,column=2)
button_clear.grid(row=4,column=1)
root.mainloop()

In [ ]:
a=[i for i in range(10000000)]
b=a=[i for i in range(10000000,20000000)]

c=[]
import time

start =time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

4.949604272842407


In [ ]:
import numpy as np
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start =time.time()
c=a+b
print(time.time()-start)

0.2638378143310547


In [ ]:
4.949604272842407/0.2638378143310547

18.76002606143414

In [ ]:
a=[i for i in range(100000)]
import sys

sys.getsizeof(a)

800984

In [ ]:
import numpy as np
a=np.arange(100000,dtype=np.int16)
sys.getsizeof(a)

: 

In [ ]:
#2D and 3D
import numpy as np
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print('hey')

hey


In [ ]:
#dtype
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [ ]:
import numpy as np
np.ones((3,4))

In [ ]:
import numpy as np
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#RANDOM VALUE IN BETWEEN 0-1
import numpy as np
np.random.random((3,4))

array([[0.82625259, 0.03094895, 0.07428161, 0.1766012 ],
       [0.31774231, 0.78417453, 0.81363711, 0.47120987],
       [0.64232173, 0.42729512, 0.78482267, 0.05405807]])

In [ ]:
#RANDOM VALUE IN BETWEEN 0-1
import numpy as np
np.random.random((300,400))

array([[0.13863831, 0.26504405, 0.87641748, ..., 0.66623646, 0.12312816,
        0.86776825],
       [0.70888942, 0.95350697, 0.62515229, ..., 0.75607052, 0.60973787,
        0.0307085 ],
       [0.49676669, 0.89334276, 0.17107289, ..., 0.76839307, 0.00756799,
        0.83359798],
       ...,
       [0.55826459, 0.90010454, 0.75569888, ..., 0.53265882, 0.29407207,
        0.65213189],
       [0.93556095, 0.26477731, 0.41126615, ..., 0.6556379 , 0.55262346,
        0.19305945],
       [0.81594455, 0.54296745, 0.84301739, ..., 0.87607269, 0.25066581,
        0.26827722]])

In [ ]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(12,dtype=np.int64).reshape(2,2,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
#ndim
a3.ndim

3

In [ ]:
print(a2.shape)
a2

(3, 4)


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [ ]:
print(a3.size)
a3

12


array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

8
8
8


In [ ]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)
print(a2)
a1

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[47., 59., 89.],
       [61., 69., 72.],
       [13.,  9., 92.]])

In [ ]:
np.prod(a1)

805053954223584.0

In [ ]:
#max/min/sum/prod
#0 -> col and 1 -> row
np.max(a1,axis=0)

array([61., 69., 92.])

In [ ]:
np.min(a1,axis=0)

array([13.,  9., 72.])

In [ ]:
np.prod(a1,axis=0)

array([ 37271.,  36639., 589536.])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1[1]

1

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a1[2:5:2]

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
print('hey')

hey


In [ ]:
print('day2')

day2


In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[82., 96., 13.],
       [29., 99., 93.],
       [66., 30., 82.]])

In [ ]:
import numpy as np 
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(36).reshape(3,3,4)
a3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [ ]:
a3[1,1:,1::2]

array([[17, 19],
       [21, 23]])

In [ ]:
a3[1,2,2]

22

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(120).reshape(10,3,4)
a3

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]],

       [[ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35]],

       [[ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59]],

       [[ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71]],

       [[ 72,  73,  74,  75],
        [ 76,  77,  78,  79],
        [ 80,  81,  82,  83]],

       [[ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95]],

       [[ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107]],

       [[108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]]])

In [ ]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)
a2


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]    

array([[1, 3],
       [5, 7]])

In [ ]:
a2[1:,0:2]

array([[4, 5],
       [8, 9]])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#if i want [0 2 18 20]
a3[::2,0,::2]
#before first comma,
#[::2] selects the matrices
#[0] gives rows
#[::2] selects the elements

array([[ 0,  2],
       [18, 20]])

In [ ]:
#if i want [[22,23],[25,26]]
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
#if i want [[9,11],[15,17]]
a3[1,::2,::2]

array([[ 9, 11],
       [15, 17]])

In [ ]:

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#if i want [[10,16],[19,25]]
a3[1:,::2,1]

array([[10, 16],
       [19, 25]])

In [ ]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
import numpy as np 
import pandas as pd
country =  ['India','Pakistan','USA','Nepal']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
dtype: object

In [ ]:
marks = [67,57,89,100]
subjects = ['maths','English','chem','Physics']
pd.Series(marks,index=subjects)

maths       67
English     57
chem        89
Physics    100
dtype: int64

In [ ]:
marks = {
    'maths':67,
    'English':57,
    'chem':89,
    'Physics':100
}

marks_series = pd.Series(marks,name='Tom Holland')
marks_series

maths       67
English     57
chem        89
Physics    100
Name: Tom Holland, dtype: int64

In [ ]:
print('hey')

hey


In [1]:
print('sup')

sup


In [8]:
#with one col
import pandas as pd
subs = pd.read_csv('subs.csv',squeeze=True)
subs

<ipython-input-8-d7e07bca6815>:3: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('subs.csv',squeeze=True)


0       48
1       57
2       40
3       43
4       44
      ... 
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [14]:
import pandas as pd
subs = pd.read_csv('movies.csv',squeeze=True)
subs


<ipython-input-14-9918f502dcd7>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('movies.csv',squeeze=True)


title_x     imdb_id  \
0                 Uri: The Surgical Strike   tt8291224   
1                            Battalion 609   tt9472208   
2     The Accidental Prime Minister (film)   tt6986710   
3                          Why Cheat India   tt8108208   
4                          Evening Shadows   tt6028796   
...                                    ...         ...   
1624                 Tera Mera Saath Rahen   tt0301250   
1625                  Yeh Zindagi Ka Safar   tt0298607   
1626                       Sabse Bada Sukh   tt0069204   
1627                                 Daaka  tt10833860   
1628                              Humsafar   tt2403201   

                                            poster_path  \
0     https://upload.wikimedia.org/wikipedia/en/thum...   
1                                                   NaN   
2     https://upload.wikimedia.org/wikipedia/en/thum...   
3     https://upload.wikimedia.org/wikipedia/en/thum...   
4                                                   NaN   
...                                                 ...   
1624  https://upload.wikimedia.org/wikipedia/en/2/2b...   
1625  https://upload.wikimedia.org/wikipedia/en/thum...   
1626                                                NaN   
1627  https://upload.wikimedia.org/wikipedia/en/thum...   
1628  https://upload.wikimedia.org/wikipedia/en/thum...   

                                              wiki_link  \
0     https://en.wikipedia.org/wiki/Uri:_The_Surgica...   
1           https://en.wikipedia.org/wiki/Battalion_609   
2     https://en.wikipedia.org/wiki/The_Accidental_P...   
3         https://en.wikipedia.org/wiki/Why_Cheat_India   
4         https://en.wikipedia.org/wiki/Evening_Shadows   
...                                                 ...   
1624  https://en.wikipedia.org/wiki/Tera_Mera_Saath_...   
1625  https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...   
1626      https://en.wikipedia.org/wiki/Sabse_Bada_Sukh   
1627                https://en.wikipedia.org/wiki/Daaka   
1628             https://en.wikipedia.org/wiki/Humsafar   

                            title_y                 original_title  is_adult  \
0          Uri: The Surgical Strike       Uri: The Surgical Strike         0   
1                     Battalion 609                  Battalion 609         0   
2     The Accidental Prime Minister  The Accidental Prime Minister         0   
3                   Why Cheat India                Why Cheat India         0   
4                   Evening Shadows                Evening Shadows         0   
...                             ...                            ...       ...   
1624          Tera Mera Saath Rahen          Tera Mera Saath Rahen         0   
1625           Yeh Zindagi Ka Safar           Yeh Zindagi Ka Safar         0   
1626                Sabse Bada Sukh                Sabse Bada Sukh         0   
1627                          Daaka                          Daaka         0   
1628                       Humsafar                       Humsafar         0   

      year_of_release runtime            genres  imdb_rating  imdb_votes  \
0                2019     138  Action|Drama|War          8.4       35112   
1                2019     131               War          4.1          73   
2                2019     112   Biography|Drama          6.1        5549   
3                2019     121       Crime|Drama          6.0        1891   
4                2018     102             Drama          7.3         280   
...               ...     ...               ...          ...         ...   
1624             2001     148             Drama          4.9         278   
1625             2001     146             Drama          3.0         133   
1626             2018      \N      Comedy|Drama          6.1          13   
1627             2019     136            Action          7.4          38   
1628             2011      35     Drama|Romance          9.0        2968   

                                              

In [12]:
import pandas as pd
subs = pd.read_csv('kohli_ipl.csv',squeeze=True)
subs

<ipython-input-12-4fbad10496a1>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('kohli_ipl.csv',squeeze=True)


match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [13]:
import pandas as pd
subs = pd.read_csv('ipl-matches.csv',squeeze=True)
subs

<ipython-input-13-f898099be034>:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('ipl-matches.csv',squeeze=True)


ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final   
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2   
2    1312198     Kolkata  2022-05-25     2022   Eliminator   
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1   
4    1304116      Mumbai  2022-05-22     2022           70   
..       ...         ...         ...      ...          ...   
945   335986     Kolkata  2008-04-20  2007/08            4   
946   335985      Mumbai  2008-04-20  2007/08            5   
947   335984       Delhi  2008-04-19  2007/08            3   
948   335983  Chandigarh  2008-04-19  2007/08            2   
949   335982   Bangalore  2008-04-18  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB

In [2]:
import pandas as pd
subs = pd.read_csv('/workspaces/codespaces-jupyter/data/ipl-matches.csv',squeeze=True)
subs

/tmp/ipykernel_8760/1005348374.py:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('/workspaces/codespaces-jupyter/data/ipl-matches.csv',squeeze=True)


ID        City        Date   Season  MatchNumber  \
0    1312200   Ahmedabad  2022-05-29     2022        Final   
1    1312199   Ahmedabad  2022-05-27     2022  Qualifier 2   
2    1312198     Kolkata  2022-05-25     2022   Eliminator   
3    1312197     Kolkata  2022-05-24     2022  Qualifier 1   
4    1304116      Mumbai  2022-05-22     2022           70   
..       ...         ...         ...      ...          ...   
945   335986     Kolkata  2008-04-20  2007/08            4   
946   335985      Mumbai  2008-04-20  2007/08            5   
947   335984       Delhi  2008-04-19  2007/08            3   
948   335983  Chandigarh  2008-04-19  2007/08            2   
949   335982   Bangalore  2008-04-18  2007/08            1   

                           Team1                        Team2  \
0               Rajasthan Royals               Gujarat Titans   
1    Royal Challengers Bangalore             Rajasthan Royals   
2    Royal Challengers Bangalore         Lucknow Super Giants   
3               Rajasthan Royals               Gujarat Titans   
4            Sunrisers Hyderabad                 Punjab Kings   
..                           ...                          ...   
945        Kolkata Knight Riders              Deccan Chargers   
946               Mumbai Indians  Royal Challengers Bangalore   
947             Delhi Daredevils             Rajasthan Royals   
948              Kings XI Punjab          Chennai Super Kings   
949  Royal Challengers Bangalore        Kolkata Knight Riders   

                                          Venue                   TossWinner  \
0              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
1              Narendra Modi Stadium, Ahmedabad             Rajasthan Royals   
2                         Eden Gardens, Kolkata         Lucknow Super Giants   
3                         Eden Gardens, Kolkata               Gujarat Titans   
4                      Wankhede Stadium, Mumbai          Sunrisers Hyderabad   
..                                          ...                          ...   
945                                Eden Gardens              Deccan Chargers   
946                            Wankhede Stadium               Mumbai Indians   
947                            Feroz Shah Kotla             Rajasthan Royals   
948  Punjab Cricket Association Stadium, Mohali          Chennai Super Kings   
949                       M Chinnaswamy Stadium  Royal Challengers Bangalore   

    TossDecision SuperOver                  WinningTeam    WonBy  Margin  \
0            bat         N               Gujarat Titans  Wickets     7.0   
1          field         N             Rajasthan Royals  Wickets     7.0   
2          field         N  Royal Challengers Bangalore     Runs    14.0   
3          field         N               Gujarat Titans  Wickets     7.0   
4            bat         N                 Punjab Kings  Wickets     5.0   
..           ...       ...                          ...      ...     ...   
945          bat         N        Kolkata Knight Riders  Wickets     5.0   
946          bat         N  Royal Challengers Bangalore  Wickets     5.0   
947          bat         N             Delhi Daredevils  Wickets     9.0   
948          bat         N          Chennai Super Kings     Runs    33.0   
949        field         N        Kolkata Knight Riders     Runs   140.0   

    method Player_of_Match                                       Team1Players  \
0      NaN       HH Pandya  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
1      NaN      JC Buttler  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
2      NaN      RM Patidar  ['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...   
3      NaN       DA Miller  ['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...   
4      NaN   Harpreet Brar  ['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...   
..     ...             ...                                                ...   
945    NaN       DJ Hussey  ['WP Saha', 'BB

In [3]:
import pandas as pd
subs = pd.read_csv('/workspaces/codespaces-jupyter/data/bollywood.csv',squeeze=True)
subs

/tmp/ipykernel_8760/2628755964.py:2: FutureWarning: The squeeze argument has been deprecated and will be removed in a future version. Append .squeeze("columns") to the call to squeeze.


  subs = pd.read_csv('/workspaces/codespaces-jupyter/data/bollywood.csv',squeeze=True)


movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [4]:
print('hey')

hey
